import { Router } from "express";
import authRole from "../middlewares/authRole";
import { adminController } from "../dependencyHandlers/admin.dependencyhandler";
import { ADMIN_ROUTES } from "../constants/routes";

const router = Router();

router.post(ADMIN_ROUTES.LOGIN, adminController.login.bind(adminController));
router.post(
  ADMIN_ROUTES.REFRESH_TOKEN,
  adminController.refreshToken.bind(adminController)
);
router.get(
  ADMIN_ROUTES.USERS,
  authRole(["admin"]),
  adminController.getAllUsers.bind(adminController)
);
router.get(
  ADMIN_ROUTES.TUTORS,
  authRole(["admin"]),
  adminController.getAllTutors.bind(adminController)
);
router.put(
  ADMIN_ROUTES.BLOCK_UNBLOCK_USER,
  authRole(["admin"]),
  adminController.blockUnblockUser.bind(adminController)
);
router.put(
  ADMIN_ROUTES.BLOCK_UNBLOCK_TUTOR,
  authRole(["admin"]),
  adminController.blockUnblockTutor.bind(adminController)
);
router.get(
  ADMIN_ROUTES.DASHBOARD,
  authRole(["admin"]),
  adminController.getDashboard.bind(adminController)
);
router.put(
  ADMIN_ROUTES.VERIFY_TUTOR,
  authRole(["admin"]),
  adminController.approveTutor.bind(adminController)
);
router.get(
  ADMIN_ROUTES.CATEGORY,
  authRole(["admin", "instructor"]),
  adminController.getCatgeories.bind(adminController)
);
router.post(
  ADMIN_ROUTES.CATEGORY,
  authRole(["admin"]),
  adminController.addCategory.bind(adminController)
);
router.patch(
  ADMIN_ROUTES.DELETE_CATEGORY,
  authRole(["admin"]),
  adminController.deleteCategory.bind(adminController)
);
router.patch(
  ADMIN_ROUTES.RESTORE_CATEGORY,
  authRole(["admin"]),
  adminController.restoreCategory.bind(adminController)
);
router.get(
  ADMIN_ROUTES.COURSES,
  authRole(["admin"]),
  adminController.getCourses.bind(adminController)
);
router.put(
  ADMIN_ROUTES.COURSE_ACTION,
  authRole(["admin"]),
  adminController.softDeleteCourse.bind(adminController)
);
router.put(
  ADMIN_ROUTES.RECOVER_COURSE,
  authRole(["admin"]),
  adminController.recoverCourse.bind(adminController)
);
router.get(
  ADMIN_ROUTES.REVIEWS,
  authRole(["admin"]),
  adminController.getAllReviews.bind(adminController)
);
router.put(
  ADMIN_ROUTES.HIDE_REVIEW,
  authRole(["admin"]),
  adminController.hideReview.bind(adminController)
);
router.put(
  ADMIN_ROUTES.UNHIDE_REVIEW,
  authRole(["admin"]),
  adminController.unhideReview.bind(adminController)
);
router.delete(
  ADMIN_ROUTES.DELETE_REVIEW,
  authRole(["admin"]),
  adminController.deleteReview.bind(adminController)
);
router.delete(
  ADMIN_ROUTES.REJECT_TUTOR,
  authRole(["admin"]),
  adminController.rejectTutor.bind(adminController)
);
router.get(
  ADMIN_ROUTES.WALLET,
  authRole(["admin"]),
  adminController.getWallet.bind(adminController)
);
router.get(
  ADMIN_ROUTES.COMPLAINTS,
  authRole(["admin"]),
  adminController.getComplaints.bind(adminController)
);
router.put(
  ADMIN_ROUTES.RESPONSE_COMPLAINT,
  authRole(["admin"]),
  adminController.responseComplaint.bind(adminController)
);
router.get(
  ADMIN_ROUTES.COURSE_STATUS,
  adminController.getCourseStats.bind(adminController)
);
router.get(
  ADMIN_ROUTES.INCOME_STATUS,
  adminController.getIncomeStats.bind(adminController)
);
router.get(
  ADMIN_ROUTES.SPECIFIC_COURSE,
  adminController.getSpecificCourseforAdmin.bind(adminController)
);
router.get(
  ADMIN_ROUTES.SPECIFIC_TUTOR,authRole(["admin"]),
  adminController.getSpecificTutor.bind(adminController)
);
router.get(
  ADMIN_ROUTES.NOTIFICATIONS,
  adminController.getNotifications.bind(adminController)
);
router.put(
  ADMIN_ROUTES.MARK_NOTIFICATION_READ,
  adminController.markAsRead.bind(adminController)
);
router.post(ADMIN_ROUTES.LOGOUT, adminController.logOut.bind(adminController));

export default router;
